# Base image with Java, Maven, and Playwright (Ubuntu Noble)
FROM mcr.microsoft.com/playwright/java:v1.50.0-noble

# Set working directory inside container
WORKDIR /app

# Set default entrypoint
ENTRYPOINT ["./entrypoint.sh"]
