services:
  spring-playwright-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: spring-playwright-app
    ports:
      - "8080:8080"
    volumes:
      - ../:/app
      - screenshot_data:/app/screenshots
    environment:
      - JAVA_OPTS=-Dspring.devtools.restart.enabled=true -Dspring.devtools.livereload.enabled=true
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - mongo
    working_dir: /app
    stdin_open: true
    tty: true

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=svuser
      - MONGO_INITDB_ROOT_PASSWORD=svpass
      - MONGO_INITDB_DATABASE=svmenu

volumes:
  mongo_data:
  screenshot_data:
