services:
  spring-playwright-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: spring-playwright-app
    ports:
      - "8080:8080"
    volumes:
      - ../:/app
    environment:
      - JAVA_OPTS=-Dspring.devtools.restart.enabled=true -Dspring.devtools.livereload.enabled=true
    working_dir: /app
    stdin_open: true
    tty: true
