name: Weekly Scrape

on:
  schedule:
    - cron: '0 6 * * 1'   # Every Monday at 06:00 UTC
  workflow_dispatch:

jobs:
  scrape_job:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Send POST request with basic auth
        run: |
          curl -X POST "${{ secrets.SCRAPE_URL }}" -H "Authorization: ${{ secrets.AUTH_HEADER }}" -u "${{ secrets.BASIC_AUTH }}"
